ARG APP_IMAGE=python:3.10.7-alpine

FROM $APP_IMAGE AS base

FROM base as builder

RUN mkdir /install
WORKDIR /install

COPY requirements.txt /requirements.txt

RUN apk update && apk add python3-dev gcc libc-dev
RUN pip install --install-option="prefix=/install" -r /requirements.txt

FROM base
ENV FLASK_APP run.py
WORKDIR /project
COPY --from=builder /install /usr/local
ADD . /project

ENTRYPOINT ["python", "-m", "flask", "run", "--host=0.0.0.0"]